### PR TITLE
Awesome books: plain JavaScript with objects

### PR DESCRIPTION
**Pull request by ntzwilly**
In this exercise we implemented the following:

A basic HTML form for a book store
A store to manage our books state tree
Functions to add and remove books from the store
Persist books to local storage

### CODE REVIEW

**Review by Temmarie — APPROVED** [review]
## Status: Invalid ❗ 

### Hi @ntzwilly  👋🏾 , 

 **While you made a great effort in this project, unfortunately, I cannot proceed to review your code.**

### Invalid Code Review Request

I have to mark this submission as invalid because you skipped the following: 
- [ ] You have to use the correct GitHub flow for this project. You will need to create a pull request to compare your `feature` branch with the `main` branch. Kindly make sure to use a more descriptive name for your branches. See [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md) for more information.




#### Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

#### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by usmansbk** [comment]
@Temmarie our feature branch is the `develop` branch and if you look closely. I merged from my forked copy `added-data-dynamically` to the original `develop` branch and finally we've created a submission PR from the original `develop` into the `main` branch. It's according to GitHub flow

**Comment by Temmarie** [comment]
Hi @ntzwilly , I apologise for that, it was an oversight, but kindly use a more descriptive name for your branches.

**Comment by usmansbk** [comment]
@Temmarie that's what we did. `added-data-dynamically` -> `develop` -> `main`. The first module lesson allows us to use `develop` as a staging branch in GitHub flow.

**Comment by Temmarie** [comment]
Please go ahead and resubmit your project for review. Sorry for the inconvenience

**Review by Temmarie — APPROVED** [review]
## Status: Approved ✔️ 
### Hi @ntzwilly  , 
#### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  Congratulations! 🎉 

#### Cheers and Happy coding!👏👏👏

_**Note: For your next milestone, kindly open a PR from the `feature` branch to the `main` branch, use descriptive names, so that the reviewer can know what the milestone is about, instead of merging to the `develop` branch and then opening the PR from there. For example, `add-books-method` to `main` . I hope this makes sense.**_


#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](<https://microverse.zendesk.com/hc/en-us/articles/1500004088561>) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](<https://airtable.com/shrQAqnBwek5a0O0s>)._

**Pull request merged**
